version: "3.8"

services:
  backend:
    image: 590183918107.dkr.ecr.us-east-1.amazonaws.com/slackerss-backend:latest
    container_name: slackers-backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production

  frontend:
    image: 590183918107.dkr.ecr.us-east-1.amazonaws.com/slackerss-frontend:latest
    container_name: slackers-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      # Tell Next.js where the backend Docker container lives (using internal Docker networking)
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - DOCKER_ENV=true
